/**
 * Crypto APIs
 * Crypto APIs 2.0 is a complex and innovative infrastructure layer that radically simplifies the development of any Blockchain and Crypto related applications. Organized around REST, Crypto APIs 2.0 can assist both novice Bitcoin/Ethereum enthusiasts and crypto experts with the development of their blockchain applications. Crypto APIs 2.0 provides unified endpoints and data, raw data, automatic tokens and coins forwardings, callback functionalities, and much more.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: bizdev@cryptoapis.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The GetFeeAddressDetailsResponseItemBalance model module.
 * @module model/GetFeeAddressDetailsResponseItemBalance
 * @version 2.0.0
 */
class GetFeeAddressDetailsResponseItemBalance {
    /**
     * Constructs a new <code>GetFeeAddressDetailsResponseItemBalance</code>.
     * Specifies the balance of the fee address.
     * @alias module:model/GetFeeAddressDetailsResponseItemBalance
     * @param amount {String} Represents the amount of the units in fee address.
     * @param unit {String} Represents the unit of the fee spent for the forwarded tokens, e.g. BTC.
     */
    constructor(amount, unit) { 
        
        GetFeeAddressDetailsResponseItemBalance.initialize(this, amount, unit);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, amount, unit) { 
        obj['amount'] = amount;
        obj['unit'] = unit;
    }

    /**
     * Constructs a <code>GetFeeAddressDetailsResponseItemBalance</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GetFeeAddressDetailsResponseItemBalance} obj Optional instance to populate.
     * @return {module:model/GetFeeAddressDetailsResponseItemBalance} The populated <code>GetFeeAddressDetailsResponseItemBalance</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetFeeAddressDetailsResponseItemBalance();

            if (data.hasOwnProperty('amount')) {
                obj['amount'] = ApiClient.convertToType(data['amount'], 'String');
            }
            if (data.hasOwnProperty('unit')) {
                obj['unit'] = ApiClient.convertToType(data['unit'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Represents the amount of the units in fee address.
 * @member {String} amount
 */
GetFeeAddressDetailsResponseItemBalance.prototype['amount'] = undefined;

/**
 * Represents the unit of the fee spent for the forwarded tokens, e.g. BTC.
 * @member {String} unit
 */
GetFeeAddressDetailsResponseItemBalance.prototype['unit'] = undefined;






export default GetFeeAddressDetailsResponseItemBalance;

