/**
 * CryptoAPIs
 * Crypto APIs 2.0 is a complex and innovative infrastructure layer that radically simplifies the development of any Blockchain and Crypto related applications. Organized around REST, Crypto APIs 2.0 can assist both novice Bitcoin/Ethereum enthusiasts and crypto experts with the development of their blockchain applications. Crypto APIs 2.0 provides unified endpoints and data, raw data, automatic tokens and coins forwardings, callback functionalities, and much more.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: developers@cryptoapis.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The GetTransactionDetailsByTransactionIDResponseItemSenders model module.
 * @module model/GetTransactionDetailsByTransactionIDResponseItemSenders
 * @version 2.0.0
 */
class GetTransactionDetailsByTransactionIDResponseItemSenders {
    /**
     * Constructs a new <code>GetTransactionDetailsByTransactionIDResponseItemSenders</code>.
     * @alias module:model/GetTransactionDetailsByTransactionIDResponseItemSenders
     * @param address {String} Represents the address which sends this transaction. In UTXO-based protocols like Bitcoin there could be several senders while in account-based protocols like Ethereum there is always only one sender.
     * @param amount {String} Represents the amount sent by this address.
     */
    constructor(address, amount) { 
        
        GetTransactionDetailsByTransactionIDResponseItemSenders.initialize(this, address, amount);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, address, amount) { 
        obj['address'] = address;
        obj['amount'] = amount;
    }

    /**
     * Constructs a <code>GetTransactionDetailsByTransactionIDResponseItemSenders</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GetTransactionDetailsByTransactionIDResponseItemSenders} obj Optional instance to populate.
     * @return {module:model/GetTransactionDetailsByTransactionIDResponseItemSenders} The populated <code>GetTransactionDetailsByTransactionIDResponseItemSenders</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetTransactionDetailsByTransactionIDResponseItemSenders();

            if (data.hasOwnProperty('address')) {
                obj['address'] = ApiClient.convertToType(data['address'], 'String');
            }
            if (data.hasOwnProperty('amount')) {
                obj['amount'] = ApiClient.convertToType(data['amount'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Represents the address which sends this transaction. In UTXO-based protocols like Bitcoin there could be several senders while in account-based protocols like Ethereum there is always only one sender.
 * @member {String} address
 */
GetTransactionDetailsByTransactionIDResponseItemSenders.prototype['address'] = undefined;

/**
 * Represents the amount sent by this address.
 * @member {String} amount
 */
GetTransactionDetailsByTransactionIDResponseItemSenders.prototype['amount'] = undefined;






export default GetTransactionDetailsByTransactionIDResponseItemSenders;

