/**
 * CryptoAPIs
 * Crypto APIs is a complex and innovative infrastructure layer that radically simplifies the development of any Blockchain and Crypto related applications. Organized around REST, Crypto APIs can assist both novice Bitcoin/Ethereum enthusiasts and crypto experts with the development of their blockchain applications. Crypto APIs provides unified endpoints and data, raw data, automatic tokens and coins forwardings, callback functionalities, and much more.
 *
 * The version of the OpenAPI document: 2021-03-20
 * Contact: developers@cryptoapis.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Cryptoapis);
  }
}(this, function(expect, Cryptoapis) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Cryptoapis.PrepareAUTXOBasedTransactionFromHDWalletXPubYPubZPubRIBSZVinInner();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('PrepareAUTXOBasedTransactionFromHDWalletXPubYPubZPubRIBSZVinInner', function() {
    it('should create an instance of PrepareAUTXOBasedTransactionFromHDWalletXPubYPubZPubRIBSZVinInner', function() {
      // uncomment below and update the code to test PrepareAUTXOBasedTransactionFromHDWalletXPubYPubZPubRIBSZVinInner
      //var instance = new Cryptoapis.PrepareAUTXOBasedTransactionFromHDWalletXPubYPubZPubRIBSZVinInner();
      //expect(instance).to.be.a(Cryptoapis.PrepareAUTXOBasedTransactionFromHDWalletXPubYPubZPubRIBSZVinInner);
    });

    it('should have the property address (base name: "address")', function() {
      // uncomment below and update the code to test the property address
      //var instance = new Cryptoapis.PrepareAUTXOBasedTransactionFromHDWalletXPubYPubZPubRIBSZVinInner();
      //expect(instance).to.be();
    });

    it('should have the property change (base name: "change")', function() {
      // uncomment below and update the code to test the property change
      //var instance = new Cryptoapis.PrepareAUTXOBasedTransactionFromHDWalletXPubYPubZPubRIBSZVinInner();
      //expect(instance).to.be();
    });

    it('should have the property derivationIndex (base name: "derivationIndex")', function() {
      // uncomment below and update the code to test the property derivationIndex
      //var instance = new Cryptoapis.PrepareAUTXOBasedTransactionFromHDWalletXPubYPubZPubRIBSZVinInner();
      //expect(instance).to.be();
    });

    it('should have the property outputIndex (base name: "outputIndex")', function() {
      // uncomment below and update the code to test the property outputIndex
      //var instance = new Cryptoapis.PrepareAUTXOBasedTransactionFromHDWalletXPubYPubZPubRIBSZVinInner();
      //expect(instance).to.be();
    });

    it('should have the property satoshis (base name: "satoshis")', function() {
      // uncomment below and update the code to test the property satoshis
      //var instance = new Cryptoapis.PrepareAUTXOBasedTransactionFromHDWalletXPubYPubZPubRIBSZVinInner();
      //expect(instance).to.be();
    });

    it('should have the property script (base name: "script")', function() {
      // uncomment below and update the code to test the property script
      //var instance = new Cryptoapis.PrepareAUTXOBasedTransactionFromHDWalletXPubYPubZPubRIBSZVinInner();
      //expect(instance).to.be();
    });

    it('should have the property sighash (base name: "sighash")', function() {
      // uncomment below and update the code to test the property sighash
      //var instance = new Cryptoapis.PrepareAUTXOBasedTransactionFromHDWalletXPubYPubZPubRIBSZVinInner();
      //expect(instance).to.be();
    });

    it('should have the property transactionId (base name: "transactionId")', function() {
      // uncomment below and update the code to test the property transactionId
      //var instance = new Cryptoapis.PrepareAUTXOBasedTransactionFromHDWalletXPubYPubZPubRIBSZVinInner();
      //expect(instance).to.be();
    });

  });

}));
